### PR TITLE
Fix buildTx for MULTIPLEOUTPUTS proposal without change

### PR DESCRIPTION
**Pull request by troggy**
Size of ``outputOrder`` array always assumes that change output will be
added. This leads to failed assertion in ``buildTx`` when no change output needed.

### CODE REVIEW

**Comment by matiu** [comment]
LGTM

**Comment by troggy** [comment]
Rebased

**Comment by troggy** [comment]
Rebased

**Comment by troggy** [comment]
Rebased

**Comment by troggy** [comment]
Not relevant anymore

**Pull request closed without merging**
